permut:	permut.o utilities.o 
	gcc -ansi -Wall -g utilities.o permut.o -o permut

permut.o: permut.c data.h
	gcc -c -ansi -Wall -g permut.c
	
utilities.o: utilities.c data.h
	gcc -c -ansi -Wall -g utilities.c 
	
	
